/* Generated by Yosys 0.66+2 (git sha1 7d3819c6b-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "npu_tile_top.v:4.1-258.10" *)
module npu_tile_top(clk, rst_n, start, done, total_cycles, bytes_read, bytes_written);
  (* src = "npu_tile_top.v:5.16-5.19" *)
  input clk;
  wire clk;
  (* src = "npu_tile_top.v:6.16-6.21" *)
  input rst_n;
  wire rst_n;
  (* src = "npu_tile_top.v:7.16-7.21" *)
  input start;
  wire start;
  (* src = "npu_tile_top.v:9.16-9.20" *)
  output done;
  reg done;
  (* src = "npu_tile_top.v:10.23-10.35" *)
  output [31:0] total_cycles;
  reg [31:0] total_cycles;
  (* src = "npu_tile_top.v:11.23-11.33" *)
  output [31:0] bytes_read;
  wire [31:0] bytes_read;
  (* src = "npu_tile_top.v:12.23-12.36" *)
  output [31:0] bytes_written;
  wire [31:0] bytes_written;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  (* force_downto = 32'd1 *)
  (* src = "npu_tile_top.v:103.29-103.45|C:\\Users\\ksmer\\DOWNLO~1\\OSS-CA~1\\bin\\../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _101_;
  (* force_downto = 32'd1 *)
  (* src = "npu_tile_top.v:103.29-103.45|C:\\Users\\ksmer\\DOWNLO~1\\OSS-CA~1\\bin\\../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _102_;
  (* src = "npu_tile_top.v:85.15-85.22" *)
  reg [4:0] counter;
  (* onehot = 32'd1 *)
  reg [8:0] state;
  (* hdlname = "u_act_sram clk" *)
  (* src = "sram_model.v:9.16-9.19" *)
  wire \u_act_sram.clk ;
  (* hdlname = "u_act_sram din" *)
  (* src = "sram_model.v:13.33-13.36" *)
  wire [127:0] \u_act_sram.din ;
  (* hdlname = "u_act_sram waddr" *)
  (* src = "sram_model.v:11.33-11.38" *)
  wire [5:0] \u_act_sram.waddr ;
  (* hdlname = "u_act_sram we" *)
  (* src = "sram_model.v:10.16-10.18" *)
  wire \u_act_sram.we ;
  (* hdlname = "u_array clk" *)
  (* src = "systolic_array_16x16.v:5.16-5.19" *)
  wire \u_array.clk ;
  (* hdlname = "u_array psum_wire[0]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[0] ;
  (* hdlname = "u_array psum_wire[10]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[10] ;
  (* hdlname = "u_array psum_wire[11]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[11] ;
  (* hdlname = "u_array psum_wire[12]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[12] ;
  (* hdlname = "u_array psum_wire[13]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[13] ;
  (* hdlname = "u_array psum_wire[14]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[14] ;
  (* hdlname = "u_array psum_wire[15]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[15] ;
  (* hdlname = "u_array psum_wire[1]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[1] ;
  (* hdlname = "u_array psum_wire[2]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[2] ;
  (* hdlname = "u_array psum_wire[3]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[3] ;
  (* hdlname = "u_array psum_wire[4]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[4] ;
  (* hdlname = "u_array psum_wire[5]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[5] ;
  (* hdlname = "u_array psum_wire[6]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[6] ;
  (* hdlname = "u_array psum_wire[7]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[7] ;
  (* hdlname = "u_array psum_wire[8]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[8] ;
  (* hdlname = "u_array psum_wire[9]" *)
  (* src = "systolic_array_16x16.v:22.19-22.28" *)
  wire [31:0] \u_array.psum_wire[9] ;
  (* hdlname = "u_array row[0].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[0].u_mac.clk ;
  (* hdlname = "u_array row[0].col[0].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[0].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[10].u_mac.clk ;
  (* hdlname = "u_array row[0].col[10].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[10].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[11].u_mac.clk ;
  (* hdlname = "u_array row[0].col[11].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[11].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[12].u_mac.clk ;
  (* hdlname = "u_array row[0].col[12].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[12].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[13].u_mac.clk ;
  (* hdlname = "u_array row[0].col[13].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[13].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[14].u_mac.clk ;
  (* hdlname = "u_array row[0].col[14].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[14].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[15].u_mac.clk ;
  (* hdlname = "u_array row[0].col[15].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[15].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[1].u_mac.clk ;
  (* hdlname = "u_array row[0].col[1].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[1].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[2].u_mac.clk ;
  (* hdlname = "u_array row[0].col[2].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[2].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[3].u_mac.clk ;
  (* hdlname = "u_array row[0].col[3].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[3].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[4].u_mac.clk ;
  (* hdlname = "u_array row[0].col[4].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[4].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[5].u_mac.clk ;
  (* hdlname = "u_array row[0].col[5].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[5].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[6].u_mac.clk ;
  (* hdlname = "u_array row[0].col[6].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[6].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[7].u_mac.clk ;
  (* hdlname = "u_array row[0].col[7].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[7].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[8].u_mac.clk ;
  (* hdlname = "u_array row[0].col[8].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[8].u_mac.psum_in ;
  (* hdlname = "u_array row[0].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[0].col[9].u_mac.clk ;
  (* hdlname = "u_array row[0].col[9].u_mac psum_in" *)
  (* src = "mac_cell.v:11.32-11.39" *)
  wire [31:0] \u_array.row[0].col[9].u_mac.psum_in ;
  (* hdlname = "u_array row[10].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[0].u_mac.clk ;
  (* hdlname = "u_array row[10].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[10].u_mac.clk ;
  (* hdlname = "u_array row[10].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[11].u_mac.clk ;
  (* hdlname = "u_array row[10].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[12].u_mac.clk ;
  (* hdlname = "u_array row[10].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[13].u_mac.clk ;
  (* hdlname = "u_array row[10].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[14].u_mac.clk ;
  (* hdlname = "u_array row[10].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[15].u_mac.clk ;
  (* hdlname = "u_array row[10].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[1].u_mac.clk ;
  (* hdlname = "u_array row[10].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[2].u_mac.clk ;
  (* hdlname = "u_array row[10].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[3].u_mac.clk ;
  (* hdlname = "u_array row[10].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[4].u_mac.clk ;
  (* hdlname = "u_array row[10].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[5].u_mac.clk ;
  (* hdlname = "u_array row[10].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[6].u_mac.clk ;
  (* hdlname = "u_array row[10].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[7].u_mac.clk ;
  (* hdlname = "u_array row[10].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[8].u_mac.clk ;
  (* hdlname = "u_array row[10].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[10].col[9].u_mac.clk ;
  (* hdlname = "u_array row[11].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[0].u_mac.clk ;
  (* hdlname = "u_array row[11].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[10].u_mac.clk ;
  (* hdlname = "u_array row[11].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[11].u_mac.clk ;
  (* hdlname = "u_array row[11].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[12].u_mac.clk ;
  (* hdlname = "u_array row[11].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[13].u_mac.clk ;
  (* hdlname = "u_array row[11].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[14].u_mac.clk ;
  (* hdlname = "u_array row[11].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[15].u_mac.clk ;
  (* hdlname = "u_array row[11].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[1].u_mac.clk ;
  (* hdlname = "u_array row[11].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[2].u_mac.clk ;
  (* hdlname = "u_array row[11].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[3].u_mac.clk ;
  (* hdlname = "u_array row[11].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[4].u_mac.clk ;
  (* hdlname = "u_array row[11].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[5].u_mac.clk ;
  (* hdlname = "u_array row[11].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[6].u_mac.clk ;
  (* hdlname = "u_array row[11].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[7].u_mac.clk ;
  (* hdlname = "u_array row[11].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[8].u_mac.clk ;
  (* hdlname = "u_array row[11].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[11].col[9].u_mac.clk ;
  (* hdlname = "u_array row[12].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[0].u_mac.clk ;
  (* hdlname = "u_array row[12].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[10].u_mac.clk ;
  (* hdlname = "u_array row[12].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[11].u_mac.clk ;
  (* hdlname = "u_array row[12].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[12].u_mac.clk ;
  (* hdlname = "u_array row[12].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[13].u_mac.clk ;
  (* hdlname = "u_array row[12].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[14].u_mac.clk ;
  (* hdlname = "u_array row[12].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[15].u_mac.clk ;
  (* hdlname = "u_array row[12].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[1].u_mac.clk ;
  (* hdlname = "u_array row[12].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[2].u_mac.clk ;
  (* hdlname = "u_array row[12].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[3].u_mac.clk ;
  (* hdlname = "u_array row[12].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[4].u_mac.clk ;
  (* hdlname = "u_array row[12].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[5].u_mac.clk ;
  (* hdlname = "u_array row[12].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[6].u_mac.clk ;
  (* hdlname = "u_array row[12].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[7].u_mac.clk ;
  (* hdlname = "u_array row[12].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[8].u_mac.clk ;
  (* hdlname = "u_array row[12].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[12].col[9].u_mac.clk ;
  (* hdlname = "u_array row[13].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[0].u_mac.clk ;
  (* hdlname = "u_array row[13].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[10].u_mac.clk ;
  (* hdlname = "u_array row[13].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[11].u_mac.clk ;
  (* hdlname = "u_array row[13].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[12].u_mac.clk ;
  (* hdlname = "u_array row[13].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[13].u_mac.clk ;
  (* hdlname = "u_array row[13].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[14].u_mac.clk ;
  (* hdlname = "u_array row[13].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[15].u_mac.clk ;
  (* hdlname = "u_array row[13].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[1].u_mac.clk ;
  (* hdlname = "u_array row[13].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[2].u_mac.clk ;
  (* hdlname = "u_array row[13].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[3].u_mac.clk ;
  (* hdlname = "u_array row[13].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[4].u_mac.clk ;
  (* hdlname = "u_array row[13].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[5].u_mac.clk ;
  (* hdlname = "u_array row[13].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[6].u_mac.clk ;
  (* hdlname = "u_array row[13].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[7].u_mac.clk ;
  (* hdlname = "u_array row[13].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[8].u_mac.clk ;
  (* hdlname = "u_array row[13].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[13].col[9].u_mac.clk ;
  (* hdlname = "u_array row[14].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[0].u_mac.clk ;
  (* hdlname = "u_array row[14].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[10].u_mac.clk ;
  (* hdlname = "u_array row[14].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[11].u_mac.clk ;
  (* hdlname = "u_array row[14].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[12].u_mac.clk ;
  (* hdlname = "u_array row[14].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[13].u_mac.clk ;
  (* hdlname = "u_array row[14].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[14].u_mac.clk ;
  (* hdlname = "u_array row[14].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[15].u_mac.clk ;
  (* hdlname = "u_array row[14].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[1].u_mac.clk ;
  (* hdlname = "u_array row[14].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[2].u_mac.clk ;
  (* hdlname = "u_array row[14].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[3].u_mac.clk ;
  (* hdlname = "u_array row[14].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[4].u_mac.clk ;
  (* hdlname = "u_array row[14].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[5].u_mac.clk ;
  (* hdlname = "u_array row[14].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[6].u_mac.clk ;
  (* hdlname = "u_array row[14].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[7].u_mac.clk ;
  (* hdlname = "u_array row[14].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[8].u_mac.clk ;
  (* hdlname = "u_array row[14].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[14].col[9].u_mac.clk ;
  (* hdlname = "u_array row[15].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[0].u_mac.clk ;
  (* hdlname = "u_array row[15].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[10].u_mac.clk ;
  (* hdlname = "u_array row[15].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[11].u_mac.clk ;
  (* hdlname = "u_array row[15].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[12].u_mac.clk ;
  (* hdlname = "u_array row[15].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[13].u_mac.clk ;
  (* hdlname = "u_array row[15].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[14].u_mac.clk ;
  (* hdlname = "u_array row[15].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[15].u_mac.clk ;
  (* hdlname = "u_array row[15].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[1].u_mac.clk ;
  (* hdlname = "u_array row[15].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[2].u_mac.clk ;
  (* hdlname = "u_array row[15].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[3].u_mac.clk ;
  (* hdlname = "u_array row[15].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[4].u_mac.clk ;
  (* hdlname = "u_array row[15].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[5].u_mac.clk ;
  (* hdlname = "u_array row[15].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[6].u_mac.clk ;
  (* hdlname = "u_array row[15].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[7].u_mac.clk ;
  (* hdlname = "u_array row[15].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[8].u_mac.clk ;
  (* hdlname = "u_array row[15].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[15].col[9].u_mac.clk ;
  (* hdlname = "u_array row[1].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[0].u_mac.clk ;
  (* hdlname = "u_array row[1].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[10].u_mac.clk ;
  (* hdlname = "u_array row[1].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[11].u_mac.clk ;
  (* hdlname = "u_array row[1].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[12].u_mac.clk ;
  (* hdlname = "u_array row[1].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[13].u_mac.clk ;
  (* hdlname = "u_array row[1].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[14].u_mac.clk ;
  (* hdlname = "u_array row[1].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[15].u_mac.clk ;
  (* hdlname = "u_array row[1].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[1].u_mac.clk ;
  (* hdlname = "u_array row[1].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[2].u_mac.clk ;
  (* hdlname = "u_array row[1].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[3].u_mac.clk ;
  (* hdlname = "u_array row[1].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[4].u_mac.clk ;
  (* hdlname = "u_array row[1].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[5].u_mac.clk ;
  (* hdlname = "u_array row[1].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[6].u_mac.clk ;
  (* hdlname = "u_array row[1].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[7].u_mac.clk ;
  (* hdlname = "u_array row[1].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[8].u_mac.clk ;
  (* hdlname = "u_array row[1].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[1].col[9].u_mac.clk ;
  (* hdlname = "u_array row[2].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[0].u_mac.clk ;
  (* hdlname = "u_array row[2].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[10].u_mac.clk ;
  (* hdlname = "u_array row[2].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[11].u_mac.clk ;
  (* hdlname = "u_array row[2].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[12].u_mac.clk ;
  (* hdlname = "u_array row[2].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[13].u_mac.clk ;
  (* hdlname = "u_array row[2].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[14].u_mac.clk ;
  (* hdlname = "u_array row[2].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[15].u_mac.clk ;
  (* hdlname = "u_array row[2].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[1].u_mac.clk ;
  (* hdlname = "u_array row[2].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[2].u_mac.clk ;
  (* hdlname = "u_array row[2].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[3].u_mac.clk ;
  (* hdlname = "u_array row[2].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[4].u_mac.clk ;
  (* hdlname = "u_array row[2].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[5].u_mac.clk ;
  (* hdlname = "u_array row[2].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[6].u_mac.clk ;
  (* hdlname = "u_array row[2].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[7].u_mac.clk ;
  (* hdlname = "u_array row[2].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[8].u_mac.clk ;
  (* hdlname = "u_array row[2].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[2].col[9].u_mac.clk ;
  (* hdlname = "u_array row[3].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[0].u_mac.clk ;
  (* hdlname = "u_array row[3].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[10].u_mac.clk ;
  (* hdlname = "u_array row[3].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[11].u_mac.clk ;
  (* hdlname = "u_array row[3].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[12].u_mac.clk ;
  (* hdlname = "u_array row[3].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[13].u_mac.clk ;
  (* hdlname = "u_array row[3].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[14].u_mac.clk ;
  (* hdlname = "u_array row[3].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[15].u_mac.clk ;
  (* hdlname = "u_array row[3].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[1].u_mac.clk ;
  (* hdlname = "u_array row[3].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[2].u_mac.clk ;
  (* hdlname = "u_array row[3].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[3].u_mac.clk ;
  (* hdlname = "u_array row[3].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[4].u_mac.clk ;
  (* hdlname = "u_array row[3].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[5].u_mac.clk ;
  (* hdlname = "u_array row[3].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[6].u_mac.clk ;
  (* hdlname = "u_array row[3].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[7].u_mac.clk ;
  (* hdlname = "u_array row[3].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[8].u_mac.clk ;
  (* hdlname = "u_array row[3].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[3].col[9].u_mac.clk ;
  (* hdlname = "u_array row[4].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[0].u_mac.clk ;
  (* hdlname = "u_array row[4].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[10].u_mac.clk ;
  (* hdlname = "u_array row[4].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[11].u_mac.clk ;
  (* hdlname = "u_array row[4].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[12].u_mac.clk ;
  (* hdlname = "u_array row[4].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[13].u_mac.clk ;
  (* hdlname = "u_array row[4].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[14].u_mac.clk ;
  (* hdlname = "u_array row[4].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[15].u_mac.clk ;
  (* hdlname = "u_array row[4].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[1].u_mac.clk ;
  (* hdlname = "u_array row[4].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[2].u_mac.clk ;
  (* hdlname = "u_array row[4].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[3].u_mac.clk ;
  (* hdlname = "u_array row[4].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[4].u_mac.clk ;
  (* hdlname = "u_array row[4].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[5].u_mac.clk ;
  (* hdlname = "u_array row[4].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[6].u_mac.clk ;
  (* hdlname = "u_array row[4].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[7].u_mac.clk ;
  (* hdlname = "u_array row[4].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[8].u_mac.clk ;
  (* hdlname = "u_array row[4].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[4].col[9].u_mac.clk ;
  (* hdlname = "u_array row[5].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[0].u_mac.clk ;
  (* hdlname = "u_array row[5].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[10].u_mac.clk ;
  (* hdlname = "u_array row[5].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[11].u_mac.clk ;
  (* hdlname = "u_array row[5].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[12].u_mac.clk ;
  (* hdlname = "u_array row[5].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[13].u_mac.clk ;
  (* hdlname = "u_array row[5].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[14].u_mac.clk ;
  (* hdlname = "u_array row[5].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[15].u_mac.clk ;
  (* hdlname = "u_array row[5].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[1].u_mac.clk ;
  (* hdlname = "u_array row[5].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[2].u_mac.clk ;
  (* hdlname = "u_array row[5].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[3].u_mac.clk ;
  (* hdlname = "u_array row[5].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[4].u_mac.clk ;
  (* hdlname = "u_array row[5].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[5].u_mac.clk ;
  (* hdlname = "u_array row[5].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[6].u_mac.clk ;
  (* hdlname = "u_array row[5].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[7].u_mac.clk ;
  (* hdlname = "u_array row[5].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[8].u_mac.clk ;
  (* hdlname = "u_array row[5].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[5].col[9].u_mac.clk ;
  (* hdlname = "u_array row[6].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[0].u_mac.clk ;
  (* hdlname = "u_array row[6].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[10].u_mac.clk ;
  (* hdlname = "u_array row[6].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[11].u_mac.clk ;
  (* hdlname = "u_array row[6].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[12].u_mac.clk ;
  (* hdlname = "u_array row[6].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[13].u_mac.clk ;
  (* hdlname = "u_array row[6].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[14].u_mac.clk ;
  (* hdlname = "u_array row[6].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[15].u_mac.clk ;
  (* hdlname = "u_array row[6].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[1].u_mac.clk ;
  (* hdlname = "u_array row[6].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[2].u_mac.clk ;
  (* hdlname = "u_array row[6].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[3].u_mac.clk ;
  (* hdlname = "u_array row[6].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[4].u_mac.clk ;
  (* hdlname = "u_array row[6].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[5].u_mac.clk ;
  (* hdlname = "u_array row[6].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[6].u_mac.clk ;
  (* hdlname = "u_array row[6].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[7].u_mac.clk ;
  (* hdlname = "u_array row[6].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[8].u_mac.clk ;
  (* hdlname = "u_array row[6].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[6].col[9].u_mac.clk ;
  (* hdlname = "u_array row[7].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[0].u_mac.clk ;
  (* hdlname = "u_array row[7].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[10].u_mac.clk ;
  (* hdlname = "u_array row[7].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[11].u_mac.clk ;
  (* hdlname = "u_array row[7].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[12].u_mac.clk ;
  (* hdlname = "u_array row[7].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[13].u_mac.clk ;
  (* hdlname = "u_array row[7].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[14].u_mac.clk ;
  (* hdlname = "u_array row[7].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[15].u_mac.clk ;
  (* hdlname = "u_array row[7].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[1].u_mac.clk ;
  (* hdlname = "u_array row[7].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[2].u_mac.clk ;
  (* hdlname = "u_array row[7].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[3].u_mac.clk ;
  (* hdlname = "u_array row[7].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[4].u_mac.clk ;
  (* hdlname = "u_array row[7].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[5].u_mac.clk ;
  (* hdlname = "u_array row[7].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[6].u_mac.clk ;
  (* hdlname = "u_array row[7].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[7].u_mac.clk ;
  (* hdlname = "u_array row[7].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[8].u_mac.clk ;
  (* hdlname = "u_array row[7].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[7].col[9].u_mac.clk ;
  (* hdlname = "u_array row[8].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[0].u_mac.clk ;
  (* hdlname = "u_array row[8].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[10].u_mac.clk ;
  (* hdlname = "u_array row[8].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[11].u_mac.clk ;
  (* hdlname = "u_array row[8].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[12].u_mac.clk ;
  (* hdlname = "u_array row[8].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[13].u_mac.clk ;
  (* hdlname = "u_array row[8].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[14].u_mac.clk ;
  (* hdlname = "u_array row[8].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[15].u_mac.clk ;
  (* hdlname = "u_array row[8].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[1].u_mac.clk ;
  (* hdlname = "u_array row[8].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[2].u_mac.clk ;
  (* hdlname = "u_array row[8].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[3].u_mac.clk ;
  (* hdlname = "u_array row[8].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[4].u_mac.clk ;
  (* hdlname = "u_array row[8].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[5].u_mac.clk ;
  (* hdlname = "u_array row[8].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[6].u_mac.clk ;
  (* hdlname = "u_array row[8].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[7].u_mac.clk ;
  (* hdlname = "u_array row[8].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[8].u_mac.clk ;
  (* hdlname = "u_array row[8].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[8].col[9].u_mac.clk ;
  (* hdlname = "u_array row[9].col[0].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[0].u_mac.clk ;
  (* hdlname = "u_array row[9].col[10].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[10].u_mac.clk ;
  (* hdlname = "u_array row[9].col[11].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[11].u_mac.clk ;
  (* hdlname = "u_array row[9].col[12].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[12].u_mac.clk ;
  (* hdlname = "u_array row[9].col[13].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[13].u_mac.clk ;
  (* hdlname = "u_array row[9].col[14].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[14].u_mac.clk ;
  (* hdlname = "u_array row[9].col[15].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[15].u_mac.clk ;
  (* hdlname = "u_array row[9].col[1].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[1].u_mac.clk ;
  (* hdlname = "u_array row[9].col[2].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[2].u_mac.clk ;
  (* hdlname = "u_array row[9].col[3].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[3].u_mac.clk ;
  (* hdlname = "u_array row[9].col[4].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[4].u_mac.clk ;
  (* hdlname = "u_array row[9].col[5].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[5].u_mac.clk ;
  (* hdlname = "u_array row[9].col[6].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[6].u_mac.clk ;
  (* hdlname = "u_array row[9].col[7].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[7].u_mac.clk ;
  (* hdlname = "u_array row[9].col[8].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[8].u_mac.clk ;
  (* hdlname = "u_array row[9].col[9].u_mac clk" *)
  (* src = "mac_cell.v:5.16-5.19" *)
  wire \u_array.row[9].col[9].u_mac.clk ;
  (* hdlname = "u_buf_sram clk" *)
  (* src = "sram_model.v:9.16-9.19" *)
  wire \u_buf_sram.clk ;
  (* hdlname = "u_rope_vec clk" *)
  (* src = "rope_vector_unit.v:4.16-4.19" *)
  wire \u_rope_vec.clk ;
  (* hdlname = "u_rope_vec gen_rope[0].u_rope clk" *)
  (* src = "rope_act_v3.v:11.16-11.19" *)
  wire \u_rope_vec.gen_rope[0].u_rope.clk ;
  (* hdlname = "u_rope_vec gen_rope[0].u_rope dim" *)
  (* src = "rope_act_v3.v:16.22-16.25" *)
  wire [5:0] \u_rope_vec.gen_rope[0].u_rope.dim ;
  (* hdlname = "u_rope_vec gen_rope[0].u_rope rst_n" *)
  (* src = "rope_act_v3.v:12.16-12.21" *)
  wire \u_rope_vec.gen_rope[0].u_rope.rst_n ;
  (* hdlname = "u_rope_vec gen_rope[1].u_rope clk" *)
  (* src = "rope_act_v3.v:11.16-11.19" *)
  wire \u_rope_vec.gen_rope[1].u_rope.clk ;
  (* hdlname = "u_rope_vec gen_rope[1].u_rope dim" *)
  (* src = "rope_act_v3.v:16.22-16.25" *)
  wire [5:0] \u_rope_vec.gen_rope[1].u_rope.dim ;
  (* hdlname = "u_rope_vec gen_rope[1].u_rope rst_n" *)
  (* src = "rope_act_v3.v:12.16-12.21" *)
  wire \u_rope_vec.gen_rope[1].u_rope.rst_n ;
  (* hdlname = "u_rope_vec gen_rope[2].u_rope clk" *)
  (* src = "rope_act_v3.v:11.16-11.19" *)
  wire \u_rope_vec.gen_rope[2].u_rope.clk ;
  (* hdlname = "u_rope_vec gen_rope[2].u_rope dim" *)
  (* src = "rope_act_v3.v:16.22-16.25" *)
  wire [5:0] \u_rope_vec.gen_rope[2].u_rope.dim ;
  (* hdlname = "u_rope_vec gen_rope[2].u_rope rst_n" *)
  (* src = "rope_act_v3.v:12.16-12.21" *)
  wire \u_rope_vec.gen_rope[2].u_rope.rst_n ;
  (* hdlname = "u_rope_vec gen_rope[3].u_rope clk" *)
  (* src = "rope_act_v3.v:11.16-11.19" *)
  wire \u_rope_vec.gen_rope[3].u_rope.clk ;
  (* hdlname = "u_rope_vec gen_rope[3].u_rope dim" *)
  (* src = "rope_act_v3.v:16.22-16.25" *)
  wire [5:0] \u_rope_vec.gen_rope[3].u_rope.dim ;
  (* hdlname = "u_rope_vec gen_rope[3].u_rope rst_n" *)
  (* src = "rope_act_v3.v:12.16-12.21" *)
  wire \u_rope_vec.gen_rope[3].u_rope.rst_n ;
  (* hdlname = "u_rope_vec gen_rope[4].u_rope clk" *)
  (* src = "rope_act_v3.v:11.16-11.19" *)
  wire \u_rope_vec.gen_rope[4].u_rope.clk ;
  (* hdlname = "u_rope_vec gen_rope[4].u_rope dim" *)
  (* src = "rope_act_v3.v:16.22-16.25" *)
  wire [5:0] \u_rope_vec.gen_rope[4].u_rope.dim ;
  (* hdlname = "u_rope_vec gen_rope[4].u_rope rst_n" *)
  (* src = "rope_act_v3.v:12.16-12.21" *)
  wire \u_rope_vec.gen_rope[4].u_rope.rst_n ;
  (* hdlname = "u_rope_vec gen_rope[5].u_rope clk" *)
  (* src = "rope_act_v3.v:11.16-11.19" *)
  wire \u_rope_vec.gen_rope[5].u_rope.clk ;
  (* hdlname = "u_rope_vec gen_rope[5].u_rope dim" *)
  (* src = "rope_act_v3.v:16.22-16.25" *)
  wire [5:0] \u_rope_vec.gen_rope[5].u_rope.dim ;
  (* hdlname = "u_rope_vec gen_rope[5].u_rope rst_n" *)
  (* src = "rope_act_v3.v:12.16-12.21" *)
  wire \u_rope_vec.gen_rope[5].u_rope.rst_n ;
  (* hdlname = "u_rope_vec gen_rope[6].u_rope clk" *)
  (* src = "rope_act_v3.v:11.16-11.19" *)
  wire \u_rope_vec.gen_rope[6].u_rope.clk ;
  (* hdlname = "u_rope_vec gen_rope[6].u_rope dim" *)
  (* src = "rope_act_v3.v:16.22-16.25" *)
  wire [5:0] \u_rope_vec.gen_rope[6].u_rope.dim ;
  (* hdlname = "u_rope_vec gen_rope[6].u_rope rst_n" *)
  (* src = "rope_act_v3.v:12.16-12.21" *)
  wire \u_rope_vec.gen_rope[6].u_rope.rst_n ;
  (* hdlname = "u_rope_vec gen_rope[7].u_rope clk" *)
  (* src = "rope_act_v3.v:11.16-11.19" *)
  wire \u_rope_vec.gen_rope[7].u_rope.clk ;
  (* hdlname = "u_rope_vec gen_rope[7].u_rope dim" *)
  (* src = "rope_act_v3.v:16.22-16.25" *)
  wire [5:0] \u_rope_vec.gen_rope[7].u_rope.dim ;
  (* hdlname = "u_rope_vec gen_rope[7].u_rope rst_n" *)
  (* src = "rope_act_v3.v:12.16-12.21" *)
  wire \u_rope_vec.gen_rope[7].u_rope.rst_n ;
  (* hdlname = "u_rope_vec rst_n" *)
  (* src = "rope_vector_unit.v:5.16-5.21" *)
  wire \u_rope_vec.rst_n ;
  (* hdlname = "u_wgt_sram clk" *)
  (* src = "sram_model.v:9.16-9.19" *)
  wire \u_wgt_sram.clk ;
  (* hdlname = "u_wgt_sram din" *)
  (* src = "sram_model.v:13.33-13.36" *)
  wire [127:0] \u_wgt_sram.din ;
  (* hdlname = "u_wgt_sram waddr" *)
  (* src = "sram_model.v:11.33-11.38" *)
  wire [5:0] \u_wgt_sram.waddr ;
  (* hdlname = "u_wgt_sram we" *)
  (* src = "sram_model.v:10.16-10.18" *)
  wire \u_wgt_sram.we ;
  assign _094_ = ~counter[0];
  assign _101_[0] = ~total_cycles[0];
  assign _095_ = total_cycles[1] & total_cycles[0];
  assign _011_ = total_cycles[2] & _095_;
  assign _012_ = total_cycles[3] & _011_;
  assign _013_ = total_cycles[4] & _012_;
  assign _014_ = total_cycles[5] & _013_;
  assign _015_ = total_cycles[6] & _014_;
  assign _016_ = total_cycles[7] & _015_;
  assign _017_ = total_cycles[8] & _016_;
  assign _018_ = total_cycles[9] & _017_;
  assign _019_ = total_cycles[10] & _018_;
  assign _020_ = total_cycles[11] & _019_;
  assign _021_ = total_cycles[12] & _020_;
  assign _022_ = total_cycles[13] & _021_;
  assign _023_ = total_cycles[14] & _022_;
  assign _024_ = total_cycles[15] & _023_;
  assign _025_ = total_cycles[16] & _024_;
  assign _026_ = total_cycles[17] & _025_;
  assign _027_ = total_cycles[18] & _026_;
  assign _028_ = total_cycles[19] & _027_;
  assign _029_ = total_cycles[20] & _028_;
  assign _030_ = total_cycles[21] & _029_;
  assign _031_ = total_cycles[22] & _030_;
  assign _032_ = total_cycles[23] & _031_;
  assign _033_ = total_cycles[24] & _032_;
  assign _034_ = total_cycles[25] & _033_;
  assign _035_ = total_cycles[26] & _034_;
  assign _036_ = total_cycles[27] & _035_;
  assign _037_ = total_cycles[28] & _036_;
  assign _038_ = total_cycles[29] & _037_;
  assign _102_[29] = total_cycles[29] ^ _037_;
  assign _102_[24] = total_cycles[24] ^ _032_;
  assign _102_[19] = total_cycles[19] ^ _027_;
  assign _102_[25] = total_cycles[25] ^ _033_;
  assign _102_[17] = total_cycles[17] ^ _025_;
  assign _102_[21] = total_cycles[21] ^ _029_;
  assign _102_[7] = total_cycles[7] ^ _015_;
  assign _102_[10] = total_cycles[10] ^ _018_;
  assign _039_ = ~(total_cycles[30] & _038_);
  assign _102_[30] = total_cycles[30] ^ _038_;
  assign _102_[1] = total_cycles[1] ^ total_cycles[0];
  assign _102_[20] = total_cycles[20] ^ _028_;
  assign _040_ = ~(state[6] | state[7]);
  assign _041_ = ~(state[2] | state[3]);
  assign _042_ = _040_ & _041_;
  assign _043_ = counter[1] & counter[0];
  assign _044_ = ~(counter[2] & _043_);
  assign _045_ = counter[2] & counter[3];
  assign _046_ = _043_ & _045_;
  assign _047_ = ~(counter[4] | _046_);
  assign _048_ = _042_ | ~(_047_);
  assign _049_ = ~(state[4] | state[1]);
  assign _050_ = _049_ & ~(state[0]);
  assign _051_ = ~(_042_ & _050_);
  assign _052_ = counter[1] & counter[4];
  assign _053_ = ~(_045_ & _052_);
  assign _054_ = _049_ | ~(_053_);
  assign _055_ = _051_ & _054_;
  assign _056_ = ~(_048_ & _055_);
  assign _057_ = ~(counter[3] ^ _044_);
  assign _099_ = _056_ & _057_;
  assign _102_[27] = total_cycles[27] ^ _035_;
  assign _102_[15] = total_cycles[15] ^ _023_;
  assign _058_ = counter[2] ^ _043_;
  assign _098_ = _056_ & _058_;
  assign _102_[31] = ~(total_cycles[31] ^ _039_);
  assign _102_[2] = total_cycles[2] ^ _095_;
  assign _059_ = ~(counter[0] | counter[2]);
  assign _060_ = _059_ & ~(counter[3]);
  assign _061_ = ~(_052_ & _060_);
  assign _062_ = _051_ | ~(_061_);
  assign _063_ = _054_ & _062_;
  assign _064_ = ~(_048_ & _063_);
  assign _065_ = counter[1] ^ counter[0];
  assign _097_ = _064_ & _065_;
  assign _102_[23] = total_cycles[23] ^ _031_;
  assign _102_[28] = total_cycles[28] ^ _036_;
  assign _096_ = _094_ & _064_;
  assign _102_[13] = total_cycles[13] ^ _021_;
  assign _102_[18] = total_cycles[18] ^ _026_;
  assign _102_[11] = total_cycles[11] ^ _019_;
  assign _102_[12] = total_cycles[12] ^ _020_;
  assign _102_[8] = total_cycles[8] ^ _016_;
  assign _102_[3] = total_cycles[3] ^ _011_;
  assign _102_[22] = total_cycles[22] ^ _030_;
  assign _102_[5] = total_cycles[5] ^ _013_;
  assign _102_[14] = total_cycles[14] ^ _022_;
  assign _102_[9] = total_cycles[9] ^ _017_;
  assign _102_[6] = total_cycles[6] ^ _014_;
  assign _102_[26] = total_cycles[26] ^ _034_;
  assign _102_[16] = total_cycles[16] ^ _024_;
  assign _066_ = rst_n & _053_;
  assign _067_ = ~(state[4] & _066_);
  assign _068_ = start & rst_n;
  assign _069_ = ~(state[0] & _068_);
  assign _004_ = ~(_067_ & _069_);
  assign _070_ = rst_n & _047_;
  assign _071_ = ~(state[3] & _070_);
  assign _072_ = rst_n & ~(_047_);
  assign _073_ = ~(state[6] & _072_);
  assign _003_ = ~(_071_ & _073_);
  assign _074_ = ~(state[7] & _070_);
  assign _075_ = ~(state[2] & _072_);
  assign _007_ = ~(_074_ & _075_);
  assign _076_ = ~(state[2] & _070_);
  assign _077_ = rst_n & ~(_053_);
  assign _078_ = ~(state[4] & _077_);
  assign _002_ = ~(_076_ & _078_);
  assign _079_ = ~(state[7] & _072_);
  assign _080_ = ~(state[1] & _066_);
  assign _001_ = ~(_079_ & _080_);
  assign _081_ = ~(state[0] | state[5]);
  assign _082_ = start | _081_;
  assign _000_ = ~(rst_n & _082_);
  assign _083_ = state[8] | _051_;
  assign _084_ = start | ~(state[0]);
  assign _085_ = rst_n & _084_;
  assign _010_ = _083_ & _085_;
  assign _086_ = ~(state[6] & _070_);
  assign _087_ = ~(state[1] & _077_);
  assign _006_ = ~(_086_ & _087_);
  assign _088_ = rst_n & state[8];
  assign _089_ = _061_ | ~(_088_);
  assign _090_ = ~(state[5] & _068_);
  assign _005_ = ~(_089_ & _090_);
  assign _091_ = ~(_061_ & _088_);
  assign _092_ = ~(state[3] & _072_);
  assign _008_ = ~(_091_ & _092_);
  assign _009_ = state[0] ? start : state[5];
  assign _093_ = counter[4] ^ _046_;
  assign _100_ = _093_ & ~(_063_);
  assign _102_[4] = total_cycles[4] ^ _012_;
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (_010_) counter[0] <= _096_;
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (_010_) counter[1] <= _097_;
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (_010_) counter[2] <= _098_;
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (_010_) counter[3] <= _099_;
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (_010_) counter[4] <= _100_;
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[0] <= 1'h0;
    else total_cycles[0] <= _101_[0];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[1] <= 1'h0;
    else total_cycles[1] <= _102_[1];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[2] <= 1'h0;
    else total_cycles[2] <= _102_[2];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[3] <= 1'h0;
    else total_cycles[3] <= _102_[3];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[4] <= 1'h0;
    else total_cycles[4] <= _102_[4];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[5] <= 1'h0;
    else total_cycles[5] <= _102_[5];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[6] <= 1'h0;
    else total_cycles[6] <= _102_[6];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[7] <= 1'h0;
    else total_cycles[7] <= _102_[7];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[8] <= 1'h0;
    else total_cycles[8] <= _102_[8];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[9] <= 1'h0;
    else total_cycles[9] <= _102_[9];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[10] <= 1'h0;
    else total_cycles[10] <= _102_[10];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[11] <= 1'h0;
    else total_cycles[11] <= _102_[11];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[12] <= 1'h0;
    else total_cycles[12] <= _102_[12];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[13] <= 1'h0;
    else total_cycles[13] <= _102_[13];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[14] <= 1'h0;
    else total_cycles[14] <= _102_[14];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[15] <= 1'h0;
    else total_cycles[15] <= _102_[15];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[16] <= 1'h0;
    else total_cycles[16] <= _102_[16];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[17] <= 1'h0;
    else total_cycles[17] <= _102_[17];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[18] <= 1'h0;
    else total_cycles[18] <= _102_[18];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[19] <= 1'h0;
    else total_cycles[19] <= _102_[19];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[20] <= 1'h0;
    else total_cycles[20] <= _102_[20];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[21] <= 1'h0;
    else total_cycles[21] <= _102_[21];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[22] <= 1'h0;
    else total_cycles[22] <= _102_[22];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[23] <= 1'h0;
    else total_cycles[23] <= _102_[23];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[24] <= 1'h0;
    else total_cycles[24] <= _102_[24];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[25] <= 1'h0;
    else total_cycles[25] <= _102_[25];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[26] <= 1'h0;
    else total_cycles[26] <= _102_[26];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[27] <= 1'h0;
    else total_cycles[27] <= _102_[27];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[28] <= 1'h0;
    else total_cycles[28] <= _102_[28];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[29] <= 1'h0;
    else total_cycles[29] <= _102_[29];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[30] <= 1'h0;
    else total_cycles[30] <= _102_[30];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) total_cycles[31] <= 1'h0;
    else total_cycles[31] <= _102_[31];
  (* src = "npu_tile_top.v:87.5-257.8" *)
  always @(posedge clk)
    if (!rst_n) done <= 1'h0;
    else if (_009_) done <= state[5];
  always @(posedge clk)
    state[0] <= _000_;
  always @(posedge clk)
    state[1] <= _001_;
  always @(posedge clk)
    state[2] <= _002_;
  always @(posedge clk)
    state[3] <= _003_;
  always @(posedge clk)
    state[4] <= _004_;
  always @(posedge clk)
    state[5] <= _005_;
  always @(posedge clk)
    state[6] <= _006_;
  always @(posedge clk)
    state[7] <= _007_;
  always @(posedge clk)
    state[8] <= _008_;
  assign _102_[0] = _101_[0];
  assign _101_[31:1] = total_cycles[31:1];
  assign \u_array.row[6].col[13].u_mac.clk  = clk;
  assign \u_array.row[11].col[2].u_mac.clk  = clk;
  assign \u_array.row[4].col[5].u_mac.clk  = clk;
  assign \u_array.row[12].col[12].u_mac.clk  = clk;
  assign \u_array.row[15].col[2].u_mac.clk  = clk;
  assign \u_array.row[0].col[5].u_mac.psum_in  = 32'd0;
  assign \u_array.row[15].col[15].u_mac.clk  = clk;
  assign \u_buf_sram.clk  = clk;
  assign \u_array.row[11].col[6].u_mac.clk  = clk;
  assign \u_array.row[6].col[0].u_mac.clk  = clk;
  assign \u_array.row[9].col[12].u_mac.clk  = clk;
  assign \u_array.row[5].col[11].u_mac.clk  = clk;
  assign \u_array.row[4].col[10].u_mac.clk  = clk;
  assign \u_array.row[0].col[7].u_mac.psum_in  = 32'd0;
  assign \u_array.row[13].col[5].u_mac.clk  = clk;
  assign \u_array.row[7].col[9].u_mac.clk  = clk;
  assign \u_array.row[10].col[5].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[1].u_rope.clk  = clk;
  assign \u_rope_vec.gen_rope[1].u_rope.rst_n  = rst_n;
  assign \u_array.row[3].col[15].u_mac.clk  = clk;
  assign \u_array.row[14].col[8].u_mac.clk  = clk;
  assign \u_array.row[5].col[7].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[1].u_rope.dim  = 6'h02;
  assign \u_array.row[1].col[11].u_mac.clk  = clk;
  assign \u_array.row[5].col[8].u_mac.clk  = clk;
  assign \u_array.row[9].col[0].u_mac.clk  = clk;
  assign \u_array.row[11].col[9].u_mac.clk  = clk;
  assign \u_array.row[5].col[14].u_mac.clk  = clk;
  assign \u_array.row[5].col[12].u_mac.clk  = clk;
  assign \u_array.row[2].col[12].u_mac.clk  = clk;
  assign \u_wgt_sram.clk  = clk;
  assign \u_wgt_sram.we  = 1'h0;
  assign \u_wgt_sram.waddr  = 6'h00;
  assign \u_array.row[0].col[8].u_mac.clk  = clk;
  assign \u_wgt_sram.din  = 128'h00000000000000000000000000000000;
  assign \u_array.row[11].col[15].u_mac.clk  = clk;
  assign \u_array.row[15].col[3].u_mac.clk  = clk;
  assign \u_array.row[12].col[4].u_mac.clk  = clk;
  assign \u_array.row[14].col[0].u_mac.clk  = clk;
  assign \u_array.row[13].col[10].u_mac.clk  = clk;
  assign \u_array.row[0].col[2].u_mac.psum_in  = 32'd0;
  assign \u_array.row[9].col[11].u_mac.clk  = clk;
  assign \u_array.row[7].col[3].u_mac.clk  = clk;
  assign \u_array.row[10].col[12].u_mac.clk  = clk;
  assign \u_array.row[0].col[0].u_mac.clk  = clk;
  assign \u_array.row[2].col[15].u_mac.clk  = clk;
  assign \u_array.row[6].col[6].u_mac.clk  = clk;
  assign \u_array.row[6].col[9].u_mac.clk  = clk;
  assign \u_array.row[7].col[10].u_mac.clk  = clk;
  assign \u_array.row[1].col[2].u_mac.clk  = clk;
  assign \u_array.row[8].col[15].u_mac.clk  = clk;
  assign \u_array.row[5].col[15].u_mac.clk  = clk;
  assign \u_array.row[2].col[3].u_mac.clk  = clk;
  assign \u_act_sram.clk  = clk;
  assign \u_act_sram.we  = 1'h0;
  assign \u_act_sram.waddr  = 6'h00;
  assign \u_array.row[14].col[9].u_mac.clk  = clk;
  assign \u_act_sram.din  = 128'h00000000000000000000000000000000;
  assign \u_rope_vec.gen_rope[6].u_rope.dim  = 6'h0c;
  assign \u_array.row[5].col[1].u_mac.clk  = clk;
  assign \u_array.row[3].col[3].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[3].u_rope.clk  = clk;
  assign \u_array.row[0].col[12].u_mac.psum_in  = 32'd0;
  assign \u_rope_vec.gen_rope[3].u_rope.rst_n  = rst_n;
  assign \u_array.row[10].col[4].u_mac.clk  = clk;
  assign \u_array.row[15].col[4].u_mac.clk  = clk;
  assign \u_array.row[4].col[14].u_mac.clk  = clk;
  assign \u_array.row[11].col[1].u_mac.clk  = clk;
  assign \u_array.row[0].col[10].u_mac.psum_in  = 32'd0;
  assign \u_rope_vec.gen_rope[2].u_rope.clk  = clk;
  assign \u_array.row[3].col[14].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[2].u_rope.rst_n  = rst_n;
  assign \u_array.row[4].col[4].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[3].u_rope.dim  = 6'h06;
  assign \u_array.row[7].col[11].u_mac.clk  = clk;
  assign \u_array.row[2].col[8].u_mac.clk  = clk;
  assign \u_array.row[0].col[12].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[2].u_rope.dim  = 6'h04;
  assign \u_array.row[5].col[4].u_mac.clk  = clk;
  assign \u_array.row[8].col[14].u_mac.clk  = clk;
  assign \u_array.row[14].col[7].u_mac.clk  = clk;
  assign \u_array.row[1].col[8].u_mac.clk  = clk;
  assign \u_array.row[2].col[2].u_mac.clk  = clk;
  assign \u_array.row[3].col[2].u_mac.clk  = clk;
  assign \u_array.row[9].col[10].u_mac.clk  = clk;
  assign \u_array.row[0].col[1].u_mac.psum_in  = 32'd0;
  assign \u_rope_vec.gen_rope[7].u_rope.dim  = 6'h0e;
  assign \u_array.row[13].col[9].u_mac.clk  = clk;
  assign \u_array.row[0].col[6].u_mac.clk  = clk;
  assign \u_array.row[12].col[15].u_mac.clk  = clk;
  assign \u_array.row[2].col[4].u_mac.clk  = clk;
  assign \u_array.row[14].col[1].u_mac.clk  = clk;
  assign \u_array.psum_wire[0]  = 32'd0;
  assign \u_array.row[15].col[5].u_mac.clk  = clk;
  assign \u_array.row[4].col[9].u_mac.clk  = clk;
  assign \u_array.row[14].col[10].u_mac.clk  = clk;
  assign \u_array.row[13].col[2].u_mac.clk  = clk;
  assign \u_array.row[11].col[5].u_mac.clk  = clk;
  assign \u_array.row[7].col[12].u_mac.clk  = clk;
  assign \u_array.row[1].col[5].u_mac.clk  = clk;
  assign \u_array.psum_wire[1]  = 32'd0;
  assign \u_array.row[10].col[11].u_mac.clk  = clk;
  assign \u_array.row[3].col[4].u_mac.clk  = clk;
  assign \u_array.row[6].col[14].u_mac.clk  = clk;
  assign \u_array.row[8].col[13].u_mac.clk  = clk;
  assign \u_array.row[11].col[11].u_mac.clk  = clk;
  assign \u_array.row[13].col[6].u_mac.clk  = clk;
  assign \u_array.row[10].col[3].u_mac.clk  = clk;
  assign \u_array.row[13].col[11].u_mac.clk  = clk;
  assign \u_array.row[9].col[9].u_mac.clk  = clk;
  assign \u_array.psum_wire[2]  = 32'd0;
  assign \u_array.row[6].col[2].u_mac.clk  = clk;
  assign \u_array.row[12].col[1].u_mac.clk  = clk;
  assign \u_array.psum_wire[3]  = 32'd0;
  assign \u_array.row[12].col[0].u_mac.clk  = clk;
  assign \u_array.row[5].col[5].u_mac.clk  = clk;
  assign \u_array.row[3].col[13].u_mac.clk  = clk;
  assign \u_array.row[15].col[6].u_mac.clk  = clk;
  assign \u_array.row[7].col[13].u_mac.clk  = clk;
  assign \u_array.psum_wire[4]  = 32'd0;
  assign \u_array.row[7].col[4].u_mac.clk  = clk;
  assign \u_array.psum_wire[5]  = 32'd0;
  assign \u_array.row[0].col[10].u_mac.clk  = clk;
  assign \u_array.psum_wire[6]  = 32'd0;
  assign \u_array.row[0].col[13].u_mac.psum_in  = 32'd0;
  assign \u_array.psum_wire[7]  = 32'd0;
  assign \u_array.row[8].col[12].u_mac.clk  = clk;
  assign \u_array.row[14].col[11].u_mac.clk  = clk;
  assign \u_array.psum_wire[8]  = 32'd0;
  assign \u_array.row[14].col[2].u_mac.clk  = clk;
  assign \u_array.psum_wire[9]  = 32'd0;
  assign \u_array.row[4].col[3].u_mac.clk  = clk;
  assign \u_array.row[1].col[10].u_mac.clk  = clk;
  assign \u_array.row[4].col[13].u_mac.clk  = clk;
  assign \u_array.row[6].col[10].u_mac.clk  = clk;
  assign \u_array.row[12].col[5].u_mac.clk  = clk;
  assign \u_array.row[9].col[8].u_mac.clk  = clk;
  assign \u_array.row[2].col[10].u_mac.clk  = clk;
  assign \u_array.row[7].col[14].u_mac.clk  = clk;
  assign \u_array.row[10].col[2].u_mac.clk  = clk;
  assign \u_array.row[3].col[5].u_mac.clk  = clk;
  assign \u_array.row[1].col[1].u_mac.clk  = clk;
  assign \u_array.row[0].col[7].u_mac.clk  = clk;
  assign \u_array.row[15].col[7].u_mac.clk  = clk;
  assign \u_array.row[11].col[13].u_mac.clk  = clk;
  assign \u_array.row[0].col[13].u_mac.clk  = clk;
  assign \u_array.row[10].col[10].u_mac.clk  = clk;
  assign \u_array.row[6].col[4].u_mac.clk  = clk;
  assign \u_array.row[12].col[11].u_mac.clk  = clk;
  assign \u_array.row[8].col[11].u_mac.clk  = clk;
  assign \u_array.row[11].col[8].u_mac.clk  = clk;
  assign \u_array.row[4].col[8].u_mac.clk  = clk;
  assign \u_array.row[0].col[0].u_mac.psum_in  = 32'd0;
  assign \u_rope_vec.gen_rope[0].u_rope.clk  = clk;
  assign \u_rope_vec.gen_rope[0].u_rope.rst_n  = rst_n;
  assign \u_array.row[11].col[0].u_mac.clk  = clk;
  assign \u_array.row[12].col[6].u_mac.clk  = clk;
  assign \u_array.row[14].col[12].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[0].u_rope.dim  = 6'h00;
  assign \u_array.row[12].col[13].u_mac.clk  = clk;
  assign \u_array.row[5].col[3].u_mac.clk  = clk;
  assign \u_array.row[7].col[5].u_mac.clk  = clk;
  assign \u_array.row[3].col[12].u_mac.clk  = clk;
  assign \u_array.row[6].col[15].u_mac.clk  = clk;
  assign \u_array.row[0].col[4].u_mac.psum_in  = 32'd0;
  assign \u_array.row[12].col[7].u_mac.clk  = clk;
  assign \u_array.row[14].col[3].u_mac.clk  = clk;
  assign \u_array.row[9].col[7].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[6].u_rope.clk  = clk;
  assign \u_array.row[7].col[15].u_mac.clk  = clk;
  assign \u_array.row[15].col[8].u_mac.clk  = clk;
  assign \u_array.row[3].col[0].u_mac.clk  = clk;
  assign \u_array.row[1].col[12].u_mac.clk  = clk;
  assign \u_array.row[8].col[10].u_mac.clk  = clk;
  assign \u_array.row[0].col[4].u_mac.clk  = clk;
  assign \u_array.row[2].col[13].u_mac.clk  = clk;
  assign \u_array.row[13].col[12].u_mac.clk  = clk;
  assign \u_array.row[10].col[1].u_mac.clk  = clk;
  assign \u_array.row[6].col[7].u_mac.clk  = clk;
  assign \u_array.row[12].col[3].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[7].u_rope.rst_n  = rst_n;
  assign \u_array.row[2].col[1].u_mac.clk  = clk;
  assign \u_array.row[3].col[6].u_mac.clk  = clk;
  assign \u_array.row[13].col[7].u_mac.clk  = clk;
  assign \u_array.row[10].col[9].u_mac.clk  = clk;
  assign \u_array.row[1].col[4].u_mac.clk  = clk;
  assign \u_array.row[11].col[4].u_mac.clk  = clk;
  assign \u_array.row[4].col[2].u_mac.clk  = clk;
  assign \u_array.row[14].col[13].u_mac.clk  = clk;
  assign \u_array.row[8].col[0].u_mac.clk  = clk;
  assign \u_array.row[5].col[9].u_mac.clk  = clk;
  assign \u_array.row[13].col[3].u_mac.clk  = clk;
  assign \u_array.row[1].col[7].u_mac.clk  = clk;
  assign \u_array.row[15].col[14].u_mac.clk  = clk;
  assign \u_array.row[15].col[9].u_mac.clk  = clk;
  assign \u_array.row[6].col[3].u_mac.clk  = clk;
  assign \u_array.row[7].col[2].u_mac.clk  = clk;
  assign \u_array.row[3].col[11].u_mac.clk  = clk;
  assign \u_array.row[10].col[6].u_mac.clk  = clk;
  assign \u_array.row[5].col[13].u_mac.clk  = clk;
  assign \u_array.row[8].col[9].u_mac.clk  = clk;
  assign \u_array.row[9].col[13].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[6].u_rope.rst_n  = rst_n;
  assign \u_array.row[9].col[6].u_mac.clk  = clk;
  assign \u_array.row[12].col[9].u_mac.clk  = clk;
  assign \u_array.row[10].col[13].u_mac.clk  = clk;
  assign \u_array.psum_wire[10]  = 32'd0;
  assign \u_array.row[15].col[1].u_mac.clk  = clk;
  assign \u_array.row[13].col[15].u_mac.clk  = clk;
  assign \u_array.row[0].col[14].u_mac.psum_in  = 32'd0;
  assign \u_array.row[4].col[15].u_mac.clk  = clk;
  assign \u_array.row[2].col[9].u_mac.clk  = clk;
  assign \u_array.row[2].col[7].u_mac.clk  = clk;
  assign \u_array.row[0].col[2].u_mac.clk  = clk;
  assign \u_array.row[0].col[5].u_mac.clk  = clk;
  assign \u_array.row[5].col[0].u_mac.clk  = clk;
  assign \u_array.row[13].col[1].u_mac.clk  = clk;
  assign \u_array.row[9].col[1].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[5].u_rope.clk  = clk;
  assign \u_rope_vec.gen_rope[5].u_rope.rst_n  = rst_n;
  assign \u_array.row[10].col[15].u_mac.clk  = clk;
  assign \u_array.row[4].col[7].u_mac.clk  = clk;
  assign \u_array.row[7].col[6].u_mac.clk  = clk;
  assign \u_array.row[14].col[4].u_mac.clk  = clk;
  assign \u_array.row[1].col[15].u_mac.clk  = clk;
  assign \u_array.row[10].col[0].u_mac.clk  = clk;
  assign \u_array.row[8].col[1].u_mac.clk  = clk;
  assign \u_array.row[6].col[11].u_mac.clk  = clk;
  assign \u_array.psum_wire[11]  = 32'd0;
  assign \u_array.psum_wire[12]  = 32'd0;
  assign \u_array.row[4].col[12].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[7].u_rope.clk  = clk;
  assign \u_array.row[1].col[0].u_mac.clk  = clk;
  assign \u_array.row[13].col[0].u_mac.clk  = clk;
  assign \u_array.row[8].col[8].u_mac.clk  = clk;
  assign \u_array.row[3].col[7].u_mac.clk  = clk;
  assign \u_array.row[14].col[14].u_mac.clk  = clk;
  assign \u_array.row[15].col[10].u_mac.clk  = clk;
  assign \u_array.row[7].col[0].u_mac.clk  = clk;
  assign \u_array.row[0].col[9].u_mac.psum_in  = 32'd0;
  assign \u_array.row[1].col[6].u_mac.clk  = clk;
  assign \u_array.row[9].col[5].u_mac.clk  = clk;
  assign \u_array.row[9].col[2].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[5].u_rope.dim  = 6'h0a;
  assign \u_array.row[12].col[14].u_mac.clk  = clk;
  assign \u_array.row[5].col[6].u_mac.clk  = clk;
  assign \u_array.row[0].col[1].u_mac.clk  = clk;
  assign \u_array.row[5].col[2].u_mac.clk  = clk;
  assign \u_array.row[13].col[13].u_mac.clk  = clk;
  assign \u_array.row[3].col[1].u_mac.clk  = clk;
  assign \u_array.row[8].col[2].u_mac.clk  = clk;
  assign \u_array.row[0].col[14].u_mac.clk  = clk;
  assign \u_array.row[10].col[8].u_mac.clk  = clk;
  assign \u_array.clk  = clk;
  assign \u_array.row[1].col[14].u_mac.clk  = clk;
  assign \u_array.row[2].col[6].u_mac.clk  = clk;
  assign \u_array.row[0].col[9].u_mac.clk  = clk;
  assign \u_array.row[11].col[10].u_mac.clk  = clk;
  assign \u_array.psum_wire[13]  = 32'd0;
  assign \u_array.row[3].col[10].u_mac.clk  = clk;
  assign \u_array.row[6].col[1].u_mac.clk  = clk;
  assign \u_array.row[1].col[13].u_mac.clk  = clk;
  assign \u_array.row[8].col[7].u_mac.clk  = clk;
  assign \u_array.row[2].col[5].u_mac.clk  = clk;
  assign \u_array.row[14].col[5].u_mac.clk  = clk;
  assign \u_array.row[4].col[1].u_mac.clk  = clk;
  assign \u_array.row[15].col[11].u_mac.clk  = clk;
  assign \u_array.row[9].col[15].u_mac.clk  = clk;
  assign \u_array.row[11].col[7].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[4].u_rope.dim  = 6'h08;
  assign \u_array.row[4].col[0].u_mac.clk  = clk;
  assign \u_array.row[13].col[8].u_mac.clk  = clk;
  assign \u_array.row[7].col[8].u_mac.clk  = clk;
  assign \u_array.row[11].col[12].u_mac.clk  = clk;
  assign \u_array.row[14].col[15].u_mac.clk  = clk;
  assign \u_array.row[8].col[3].u_mac.clk  = clk;
  assign \u_array.row[12].col[8].u_mac.clk  = clk;
  assign \u_array.row[11].col[14].u_mac.clk  = clk;
  assign \u_array.row[9].col[4].u_mac.clk  = clk;
  assign \u_array.row[2].col[0].u_mac.clk  = clk;
  assign \u_array.row[1].col[3].u_mac.clk  = clk;
  assign \u_array.row[15].col[13].u_mac.clk  = clk;
  assign \u_array.row[0].col[8].u_mac.psum_in  = 32'd0;
  assign \u_array.row[7].col[7].u_mac.clk  = clk;
  assign \u_array.row[2].col[11].u_mac.clk  = clk;
  assign \u_array.psum_wire[14]  = 32'd0;
  assign \u_array.row[0].col[11].u_mac.psum_in  = 32'd0;
  assign \u_array.row[3].col[8].u_mac.clk  = clk;
  assign \u_array.psum_wire[15]  = 32'd0;
  assign \u_array.row[6].col[8].u_mac.clk  = clk;
  assign \u_array.row[0].col[3].u_mac.psum_in  = 32'd0;
  assign \u_array.row[11].col[3].u_mac.clk  = clk;
  assign \u_array.row[12].col[2].u_mac.clk  = clk;
  assign \u_array.row[8].col[6].u_mac.clk  = clk;
  assign \u_array.row[6].col[5].u_mac.clk  = clk;
  assign \u_array.row[7].col[1].u_mac.clk  = clk;
  assign \u_array.row[1].col[9].u_mac.clk  = clk;
  assign \u_array.row[6].col[12].u_mac.clk  = clk;
  assign \u_array.row[15].col[12].u_mac.clk  = clk;
  assign \u_array.row[10].col[14].u_mac.clk  = clk;
  assign \u_array.row[8].col[4].u_mac.clk  = clk;
  assign \u_array.row[4].col[6].u_mac.clk  = clk;
  assign \u_array.row[10].col[7].u_mac.clk  = clk;
  assign \u_array.row[0].col[15].u_mac.psum_in  = 32'd0;
  assign \u_array.row[0].col[11].u_mac.clk  = clk;
  assign \u_array.row[12].col[10].u_mac.clk  = clk;
  assign \u_array.row[0].col[3].u_mac.clk  = clk;
  assign \u_array.row[13].col[4].u_mac.clk  = clk;
  assign \u_array.row[9].col[14].u_mac.clk  = clk;
  assign \u_array.row[0].col[15].u_mac.clk  = clk;
  assign \u_array.row[3].col[9].u_mac.clk  = clk;
  assign \u_array.row[9].col[3].u_mac.clk  = clk;
  assign \u_array.row[15].col[0].u_mac.clk  = clk;
  assign \u_array.row[5].col[10].u_mac.clk  = clk;
  assign \u_array.row[14].col[6].u_mac.clk  = clk;
  assign \u_array.row[8].col[5].u_mac.clk  = clk;
  assign \u_array.row[13].col[14].u_mac.clk  = clk;
  assign \u_array.row[2].col[14].u_mac.clk  = clk;
  assign \u_array.row[0].col[6].u_mac.psum_in  = 32'd0;
  assign \u_array.row[4].col[11].u_mac.clk  = clk;
  assign \u_rope_vec.gen_rope[4].u_rope.clk  = clk;
  assign \u_rope_vec.gen_rope[4].u_rope.rst_n  = rst_n;
  assign \u_rope_vec.rst_n  = rst_n;
  assign \u_rope_vec.clk  = clk;
  assign bytes_written = 32'd0;
  assign bytes_read = 32'd0;
endmodule
